FROM almalinux:9
RUN dnf install nginx -y
RUN rm -rf usr/share/nginx/html/index.html
ADD https://raw.githubusercontent.com/iam-veeramalla/Docker-Zero-to-Hero/refs/heads/main/README.md usr/share/nginx/html/index.html
RUN chmod +r usr/share/nginx/html/index.html
CMD ["nginx", "-g", "daemon off;"]