ARG version
FROM almalinux:${version:-9}
ENV from="Vizag" \
    to="Hyderabad" 
ARG duration="16HRS"
ENV version=$version
RUN echo "Hi, Source is: ${from}, Destination is: ${to}, Duration is: ${duration} , Version is: ${version}"
CMD ["sleep", "1000"]